
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "IDENTIFIER PREPROCESSING_NUMBER STRING_LITERAL PUNCTUATOR WHITESPACE OTHER PREPROCESSING_KEYWORD_INCLUDE PREPROCESSING_KEYWORD_DEFINE\n    program : statements\n    \n    statements :\n    \n    statements : statements statement\n    \n    statement   : pepper_directive\n    \n    pepper_directive : preprocessor_expression\n    \n    preprocessor_expression : include_expression\n    \n    include_expression : '#' PREPROCESSING_KEYWORD_INCLUDE STRING_LITERAL\n    \n    include_expression : '#' PREPROCESSING_KEYWORD_INCLUDE '<' IDENTIFIER '>'\n    "
    
_lr_action_items = {'#':([0,2,4,5,6,7,9,12,],[-2,3,-5,-3,-6,-4,-7,-8,]),'$end':([0,1,2,4,5,6,7,9,12,],[-2,0,-1,-5,-3,-6,-4,-7,-8,]),'PREPROCESSING_KEYWORD_INCLUDE':([3,],[8,]),'IDENTIFIER':([10,],[11,]),'>':([11,],[12,]),'STRING_LITERAL':([8,],[9,]),'<':([8,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'preprocessor_expression':([2,],[4,]),'program':([0,],[1,]),'include_expression':([2,],[6,]),'statements':([0,],[2,]),'statement':([2,],[5,]),'pepper_directive':([2,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parser.py',12),
  ('statements -> <empty>','statements',0,'p_statements_empty','parser.py',19),
  ('statements -> statements statement','statements',2,'p_statements_nonempty','parser.py',26),
  ('statement -> pepper_directive','statement',1,'p_statement_rules','parser.py',34),
  ('pepper_directive -> preprocessor_expression','pepper_directive',1,'p_pepper_directive','parser.py',41),
  ('preprocessor_expression -> include_expression','preprocessor_expression',1,'p_expression','parser.py',48),
  ('include_expression -> # PREPROCESSING_KEYWORD_INCLUDE STRING_LITERAL','include_expression',3,'p_include_expression_file','parser.py',55),
  ('include_expression -> # PREPROCESSING_KEYWORD_INCLUDE < IDENTIFIER >','include_expression',5,'p_include_expression_system','parser.py',62),
]
