# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PEPPr: Python Enhanced PreProcessor
  Google search results) and in your feed.xml site description.
baseurl: "/pepper" # the subpath of your site, e.g. /blog
url: "https://devosoft.github.io" # the base hostname & protocol for your site
github_username:  devosoft

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
